config/routes.rb
Rails.application.routes.draw do
  devise_for :sellers
    devise_for :users
  devise_for :models
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
      get 'shopping_cart/all'
      
      get 'orders/all'
      
      get '/orders/:id', to: 'orders#products', as: 'orders'
       root to: "shopping_cart#index"
        resources :shopping_cart, as: :product  do 
              resources :orders
          end



        get 'seller_side_products/all'
        root to: "seller_side_products_controller#index"
        resources :seller_side_products

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/final_order.rb
class FinalOrder < ApplicationRecord
	belongs_to :user
end

app/models/final_order_list.rb
class FinalOrderList < ApplicationRecord
	#belongs_to :order, dependent: :destroy
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
	has_and_belongs_to_many :product_seller, :join_table => 'order_product_sellers'
	belongs_to :user
	#belongs_to :final_order_list, dependent: :destroy

end

app/models/order_product_seller.rb
class OrderProductSeller < ApplicationRecord
  belongs_to :order
  belongs_to :product_seller
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/product_seller.rb
class ProductSeller < ApplicationRecord
has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	has_and_belongs_to_many :order , :join_table => 'order_product_sellers'
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_one :order
         has_one :final_order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
   def after_sign_in_path_for(resource_or_scope)
    if current_user
    	product_index_path
    elsif current_seller
    	seller_side_products_path
    else
    	new_user_session_path
  	end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def all
		@orders = Order.where(:user_id => current_user.id)
		#@pro_id= params[:product_id]
		#@final_order = FinalOrderList.where(:user_id => current_user.id)
	end

	def new
		
		@order = Order.new
		

		@order = ProductSeller.find(params[:product_id])
	end

	

	def create
			@order = Order.new(active_paramss)
			@product_seller = ProductSeller.find(params[:product_id])
			@order.user_id =current_user.id

		if @order.save
			@order_product_seller= OrderProductSeller.create(:order_id => @order.id, :product_seller_id => @product_seller.id)
			redirect_to product_order_path(@product_seller,@order)
		else
			render 'new'
		end

	
	end

	def show

		@order = Order.find(params[:id])

		
	end
		def index 

		@orders = Order.where(:user_id => current_user.id)
		@pro_id= params[:product_id]
		@orders.each do |t|
		@final_order = FinalOrderList.create(pro_name: t.pro_name, price: t.price, units: t.units, user_id: current_user.id)

	end

		end

	

	def edit
		@order = Order.find(params[:id])
	end

	def update
		@order = Order.find(params[:id])
		
		if @order.update(active_paramss)
			redirect_to @order
		else
			render 'edit'
		end
	end

	def destroy

		@order = Order.find(params[:id])
		@order_product_seller = OrderProductSeller.find_by(:order_id => @order.id)
		@pro_id=@order_product_seller.product_seller_id
		if @order.destroy
			
		redirect_to product_orders_path(@pro_id)
		else
		 flash[:error] = "Order has not been deleted due to some error"
		end
	end


	def products
		@orders = Order.find(params[:id])
		
		@order_product= ProductSeller.find_by(:pro_name => @orders.pro_name)
	end


	private 
	def active_paramss
		
		params.require(:order).permit(:pro_name, :price, :units)

	end




end

app/controllers/seller_side_products_controller.rb
class SellerSideProductsController < ApplicationController
	def create
	
		@product_seller = ProductSeller.new(active_params)
		
		if @product_seller.save
			redirect_to seller_side_product_path(@product_seller)
		else
			render 'new'
		end
	end

	def all
		@product_seller = ProductSeller.all
	end
	def show
		@product_seller = ProductSeller.find(params[:id])
	end

	def edit
		@product_seller = ProductSeller.find(params[:id])
		
	end

	def destroy
		@product_seller = ProductSeller.find(params[:id])
		@product_seller.destroy
		redirect_to seller_side_products_all_path
	end

	def update
		@product_seller = ProductSeller.find(params[:id])
		
		if @product_seller.update(active_params)
			redirect_to seller_side_product_path(@product_seller)
		else
			render 'edit'
		end
	end


	private 
	def active_params
		params.require(:product_seller).permit(:pro_name, :price, :units, :avatar)
	end
end

app/controllers/shopping_cart_controller.rb
class ShoppingCartController < ApplicationController
	


	def all
		@products = ProductSeller.all
	end

	def show
		@products = ProductSeller.find(params[:id])  
		
	end

	
	


	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/seller_side_products_helper.rb
module SellerSideProductsHelper
end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
  
  </head>

  <body style="background: #f5f5f5;">
    <p class="alert"><%= alert %></p>
    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <span class="glyphicon glyphicon-cloud"></span>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href=/shopping_cart/all >Products</a></li>
        
        <li><a href="#">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
       <li>
       <div>
        <div class="dropdown">
             <button class="btn btn-primary dropdown-toggle" type="button" id="menu1" data-toggle="dropdown" style="background: #101010;
             padding-bottom: 14px;
             border-color: #101010;
             padding-top: 14px;">
             <% if current_user%>
                  <%= current_user.email%>
             <% elsif current_seller %>
               <%= current_seller.email%>
               <%else %>
             <%end%> <span class="caret"></span></button>
             <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
               <li role="presentation"><a role="menuitem" tabindex="-1" href="#">
                    <% if user_signed_in? %>
                 <%= link_to 'ACCOUNT' , edit_user_registration_path%>            
               <%elsif seller_signed_in? %>
                  
                 <%= link_to 'ACCOUNT' , edit_seller_registration_path%>

                
               <% else %>

                 <% end %></a></li>
               <li role="presentation"><a role="menuitem" tabindex="-1" href="#">SETTING</a></li>
               <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><% if user_signed_in? %>
               <%= link_to 'LOGOUT' , destroy_user_session_path, method: :DELETE %>
                 
           <%elsif seller_signed_in? %>
              
             || <%= link_to 'LOGOUT' , destroy_seller_session_path, method: :DELETE %>
            
           <% else %>

             <% end %></li>
               <li role="presentation" class="divider"></li>
               <li role="presentation"><a role="menuitem" tabindex="-1" href="#">About Us</a></li>
             </ul>
           </div>
           </li>
                 <li><a href=/orders/all ><span class="glyphicon glyphicon-shopping-cart"></span> Cart</a></li>

               </ul>
    </div>
    </div>
  </div>
</nav>
  	
    
    <%= yield %>
  </body>
</html>

app/views/orders/all.html.erb
 <div class="container">
  <h2 style="text-align: center; color: #337ab7;">FINAL ORDER</h2>
  <br><br><br>
                                                                                       
  <div class="table-responsive">          
  <table class="table">
    <thead>
 	<tr><th>ID</th>
 	<th>PRODUCT NAME:</th>
    <th>PRICE:</th>
    <th>UNITS:</th>
    <th>TOTAL PRICE</th>
 	</tr>
 </thead><% a= 0%>
  <% b= 0%>
  <tbody> <% @orders.each do |article| %>
    <tr>
      <td><%= b+=1%></td>
      <td><%= link_to (article.pro_name), orders_path(article)%></td>
      <td><%= article.price %></td>
      <td><%= article.units %></td>
  	  <td><%= article.units*article.price %></td>
  	  <% a= article.units*article.price + a%>
    </tr><%end%>
    <td></td>
  <th style="font-size: xx-large;">GRAND TOTAL</th>
  <td></td>
  <td></td>
  <td style="font-size: xx-large; background: #337ab7; color: blanchedalmond"><%= a%></td>
  
 </tr>
</tbody>
</table>

 <%= link_to 'Back', product_index_path%>
      
  
 </div>


<ul class="pager">
    <li class="previous"><a href="./new">Previous</a></li>
    <li class="next"><a href="./">Next</a></li>
  </ul>

app/views/orders/index.html.erb
 <div class="container">
  <h2 style="text-align: center; color: #337ab7;">FINAL ORDER</h2>
  <br><br><br>
                                                                                       
  <div class="table-responsive">          
  <table class="table">
    <thead>
  <tr><th>ID</th>
  <th>PRODUCT NAME:</th>
    <th>PRICE:</th>
    <th>UNITS:</th>
    <th>TOTAL PRICE</th>
  </tr>
 </thead><% a= 0%>
  <% b= 0%>
  <tbody> <% @orders.each do |article| %>
    <tr>
      <td><%= b+=1%></td>
      <td><%= link_to (article.pro_name), orders_path(article)%></td>
      <td><%= article.price %></td>
      <td><%= article.units %></td>
      <td><%= article.units*article.price %></td>
      <% a= article.units*article.price + a%>
      <td><%= link_to 'destroy' ,product_order_path(product_id: @pro_id,id: article.id),  method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      

    </tr><%end%>
    <td></td>
  <th style="font-size: xx-large;">GRAND TOTAL</th>
  <td></td>
  <td></td>
  <td style="font-size: xx-large; background: #337ab7; color: blanchedalmond"><%= a%></td>
  
 </tr>
</tbody>
</table>

 <%= link_to 'Back', product_index_path%>
      
  
 </div>


 <h1><a href=/shopping_cart/all class="btn btn-default btn-block"  role="button">ADD MORE PRODUCTS</a></h1>
 <h1><a href=/orders/all class="btn btn-default btn-block"  role="button">MY ORDER</a></h1>


<ul class="pager">
    <li class="previous"><a href="./new">Previous</a></li>
    <li class="next"><a href="./">Next</a></li>
  </ul>

app/views/orders/new.html.erb
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class="container" style="text-align: center fo" >


  


<%= form_for :order, url: product_orders_path(params[:product_id])do |f| %>

  <p>
    <%= f.label :pro_name,Product%><br>
    <%= f.text_field :pro_name %>
 
    
  </p>
 
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>

  </p>
  <p>
    <%= f.label :units %>: 
  
  <%= f.select(:units, options_for_select(['5', '4', '3', '2', '1'], 3), {},style: "width: 30px") %> 
  </p>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
</div>


<ul class="pager">
    <li ><a href="./new">Previous</a></li>
    <li ><a href="./">Next</a></li>
  </ul>

app/views/orders/products.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<h1>

    <h1 style="text-align: center">PRODUCTS</h1> 
<div class="container" >
  <div class="col-sm-6" style="float: left">
  
<table>
   <tr>
    <th>PRODUCT NAME:</th>    
    <td><%= @order_product.pro_name %></td>
   </tr>
   <tr> 
    <th>PRICE:</th>   
    <td><%= @order_product.price %></td>  
   </tr>
   <tr> 
    <th>TOTAL PRICE</th>    
    <th><%= @order_product.units*@order_product.price %></th>
   </tr>  
</table>
  </div>
 
    <div class="col-sm-6" style="float: right"><%= image_tag @order_product.avatar.url %></div>
<br><br><br>
</div>
<p>
    <h1> <a href="./all" class="btn btn-default btn-block" role="button">'Back'</a></h1>
  </p>

</h1>
 

 <ul class="pager">
    <li class="previous"><a href="./new">Previous</a></li>
    <li class="next"><a href="./">Next</a></li>
  </ul>

app/views/orders/show.html.erb
 <h1 style="text-align: center; color: #337ab7">PRODUCTS</h1>



  <div class="table-responsive" style="padding-left: 50px;
    padding-right: 50px;">          
  <table class="table" >
    <thead>
  <tr>
  <th>PRODUCT NAME:</th>
    <th>PRICE:</th>
    <th>UNITS:</th>
    <th>TOTAL PRICE</th>
  </tr>
 </thead><% a= 0%>
  <% b= 0%>
  <tbody> 
    <tr>

      <td><%= @order.pro_name %></td>
      <td><%= @order.price %></td>
      <td><%= @order.units %></td>
      <td><%= @order.units*@order.price %></td>
      <td><%= link_to 'Back',product_orders_path %></td>
      

    <td>
</tbody>
</table>



 <%= link_to 'Back', product_index_path%>
      
  
 </div>

 <ul class="pager">
    <li class="previous"><a href="./new">Previous</a></li>
    <li class="next"><a href="./">Next</a></li>
  </ul>

app/views/seller_side_products/_form.html.erb
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class="container" >
<%= form_for @product_seller, url: seller_side_products_path, html: { multipart: true } do |f| %>
  <p>
    <%= f.label :pro_name %><br>
    <%= f.text_field :pro_name %>
  </p>
 
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :units %>: 
  
  <%= f.select(:units, options_for_select(['5', '4', '3', '2', '1'], 3), {},style: "width: 30px") %> 
  </p>
  <p>
    
     <%= f.file_field :avatar %>
     
  </p>
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
</div>

app/views/seller_side_products/all.html.erb
 <h1 style="text-align: center; color: #337ab7">PRODUCTS</h1>
 <br><br>
<div class="container">
 <table>
 	<tr><th>SERIAL NO</th>
 	<th>PRODUCT NAME:</th>
    <th>PRICE:</th>
    <th>UNITS:</th>
    <th>TOTAL PRICE</th><th>VIEW</th>
    <th></th>
<th></th>
 	</tr>
 <% @product_seller.each do |article| %>
    <tr><td><%= article.id %></td>
      <td><%= article.pro_name %></td>
      <td><%= article.price %></td>
      <td><%= article.units %></td>
  	  <td><%= article.units*article.price %></td>
  	  
      <td><%= link_to (image_tag article.avatar.url(:thumb)) ,seller_side_product_path(article) %></td>
      <td><%= link_to 'edit' ,edit_seller_side_product_path(article) %></td>
      <td><%= link_to 'destroy' ,seller_side_product_path(article),  method: :delete,
              data: { confirm: 'Are you sure?' } %></td>  </tr>
  <% end %>
    
 </table>
 </div>

 <ul class="pager">
    <li class="previous"><a href="./new">Previous</a></li>
    <li class="next"><a href="./">Next</a></li>
  </ul>

app/views/seller_side_products/create.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<div class="container">
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">Home</a></li>
    <li><a data-toggle="tab" href="#menu1"></a></li>
    <li><a data-toggle="tab" href="#menu2">Menu 2</a></li>
    <li><a data-toggle="tab" href="#menu3">Menu 3</a></li>
  </ul>
  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
      <h3></h3>
   </div>
    <div id="menu1" class="tab-pane fade">
      <h3>Menu 1</h3>
    </div>
    <div id="menu2" class="tab-pane fade">
      <h3>Menu 2</h3>
    </div>
    <div id="" class="tab-pane fade">
      <h3>Menu 3</h3>
    </div>
  </div>

  <ul class="pager">
    <li class="previous"><a href="./new">Previous</a></li>
    <li class="next"><a href="./">Next</a></li>
  </ul>

app/views/seller_side_products/edit.html.erb
<div class="container">
  <h1 style="backgrount_color: #46b8da;    color: #337ab7;">EDIT PRODUCT</h1>
</div>

<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class="container" >
<%= form_for @product_seller, url: seller_side_product_path(@product_seller), method: :patch, html: { multipart: true } do |f| %>
  <p>
    <%= f.label :pro_name %><br>
    <%= f.text_field :pro_name %>
  </p>
 
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :units %>: 
  
  <%= f.select(:units, options_for_select(['5', '4', '3', '2', '1'], 3), {},style: "width: 30px") %> 
  </p>
  <p>
    
     <%= f.file_field :avatar %>
     
  </p>
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
</div>
  <div class="container">
 <p>
    <h1> <a href=/seller_side_products/all class="btn btn-default btn-block" role="button">'Back'</a></h1>
  </p>
</div>

<ul class="pager">
    <li class="previous"><a href="./new">Previous</a></li>
    <li class="next"><a href="./">Next</a></li>
  </ul>

app/views/seller_side_products/index.html.erb
<h1 style="text-align: center;     color: #337ab7;">
  Welcome to the Seller app
<br><br><br><br>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>



<%= form_for :cart do |f| %>
 <h1><a href=/seller_side_products/new class="btn btn-default btn-block"   role="button">ADD NEW PRODUCT</a></h1>
 <h1><a href=/seller_side_products/all class="btn btn-default btn-block"  role="button">SHOW ALL PRODUCTS</a></h1>
</div>
<% end %>

<ul class="pager">
    <li class="previous"><a href="./new">Previous</a></li>
    <li class="next"><a href="./">Next</a></li>
  </ul>

app/views/sellers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/shopping_cart/all.html.erb
 
 <h1 style="text-align: center; color: #337ab7">PRODUCTS</h1>

 

<div class="container">   

  <% @products.each do |article| %>
  <div class="col-sm-4">
      <div id="img">
      <%= link_to (image_tag article.avatar.url),product_path(article)%>
      </div>
      
      <td><%= link_to 'show or buy' ,product_path(article) %></td>
      
  </div>
<% end %>  
</div>
<ul class="pager">
    <li class="previous"><a href="./">Previous</a></li>
    
  </ul>

app/views/shopping_cart/new.html.erb
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class="container" >
<%= form_for :[@order, @order.product.build] url: product_orders_path(@products) do |f| %>

<th>PRODUCT NAME:</th>
<td><%= @products.pro_name %></td>
<th>PRICE:</th>
<td><%= @products.price %></td>  

  <p>
    <%= f.label :units %>: 
  
  <%= f.select(:units, options_for_select(['5', '4', '3', '2', '1'], 3), {},style: "width: 30px") %> 
  </p>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
</div>

<ul class="pager">
    <li><a href="./new">Previous</a></li>
    <li><a href="./">Next</a></li>
  </ul>

app/views/shopping_cart/show.html.erb
<div>


<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</div>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<b>
    <h1 style="text-align: center; font-family: fantasy;">PRODUCTS</h1> 
     <div class="row" style="padding-left: 131px; font-family: fantasy;">

          <div class="col-sm-6" >
            <h3>PRODUCT NAME: <%= @products.pro_name %></h3>
            <h3>PRICE: <%= @products.price %></h3>
            <h3>UNITS: <%= @products.units %></h3>
               <h3>TOTAL PRICE</h3>
              <h3><%= @products.units*@products.price %></h3>
            </div>
       
<div class="col-sm-4" style="float: right"><%= image_tag @products.avatar.url %></div>
</div>

<br><br><br>
<p>
    <h1> <a href=/shopping_cart/all class="btn btn-default btn-block" role="button">'Back'</a></h1>
  </p>
</b>
</h1>
 
<ul class="pager">
    <li><a href="./new">Previous</a></li>
    <li ><%= link_to 'ADD TO CART' , new_product_order_path(@products)%></li>
</ul>